name: matrix-workflow
on: push

jobs:
  checkout:
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        os: [ubuntu-latest,ubuntu-24.04, windows-latest]
        image: [httpd:latest,nginx:latest]
        exclude:
          - os: windows-latest
            image: [httpd:latest,nginx:latest]
    runs-on: ${{matrix.os}}
    steps: 
      - name: checkout
        uses: actions/checkout@v4
      - name: github context
        run: |
         echo "Repository name is $GITHUB_REF"
         echo "Triggered by $GITHUB_TRIGGER"
         echo "Event type is ${{ github.event_name }}"
         echo "Event type is ${{strategy.job-index}}"
         echo "Event type is ${{strategy.job-total}}"
         echo "Event type is ${{strategy.fail-fast}}"
         echo "Secret value is ${{secrets.GITHUB_TOKEN}}"
      - name: docker version
        run: |
          docker info
          echo "Runs on ${{runner.os}}"

      - name: docker pull and deploy on ${{matrix.image}}
        run: docker run -d -t -p 80:80 ${{matrix.image}}