name: matrix-workflow
on: push
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: check docker version
        run: docker --version
  docker-os:
    runs-on: ubuntu-latest
    steps:
      - name : build and run
        run: |
          docker run -d -t -p 80:80 httpd:latest
      
  