name: Matrix-workflow
on: push

jobs:
  matrox:
    strategy:
      matrix:
        image: [hello-world,httpd,nginx]
        os: [ubunt-latest,ubuntu-20.02]
    runs-on: ${{matrix.os}}
    steps:
      - name: Echo Docker Images
        run: docker info
      - name: Run image on ${{matrix.image}}
        run: docker run ${{matrix.image}}