name: matrix-workflow
on: push

jobs:
  checkout:
    strategy:
      matrix:
        os : [ubuntu-latest, windows-latest]
        image: [httpd:latest,nginx:latest]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: check docker version
        run: docker --version
  docker-os:
    runs-on: ${{matrix.os}}
    steps:
      - name : build and run on ${{matrix.os}}
        run: |
          docker run -d -t -p 80:80 ${{matrix.image}}
      
  