name: matrix-workflow
on: push

jobs:
  checkout:
    strategy:
      matrix:
        os: [ubuntu-latest,ubuntu-24.04]
        image: [httpd:latest,nginx:latest]
      fail-fast: true
    runs-on: ${{matrix.os}}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: docker version
        run: docker --version
      - name: docker pull and deploy on ${{matrix.image}}
        run: docker run -d -t -p 80:80 ${{matrix.image}}
      
  